export const mockData = [
  {
    id: 'ABCD-1234-ABCD-5555',
    brand: 'BMW',
    model: 'i5',
    year: 2024,
    hourPrice: 1255.5,
    color: 'red',
    transmission: 'Automatic',
    fuelType: 'Electric',
    seat: 4,
    avaliable: true,
    createdDate: new Date(),
    updatedDate: new Date(),
  },
  {
    id: 'ZXCV-5678-ZXCV-7777',
    brand: 'Audi',
    model: 'A3',
    year: 2020,
    hourPrice: 775.25,
    color: 'black',
    transmission: 'Manual',
    fuelType: 'Petrol',
    seat: 4,
    avaliable: false,
    createdDate: new Date(),
    updatedDate: new Date(),
  },
];
